MERGE INTO YEARS (ID_YEAR, RELEASE_YEAR) KEY(ID_YEAR) VALUES (1, 2014);
MERGE INTO YEARS (ID_YEAR, RELEASE_YEAR) KEY(ID_YEAR) VALUES (2, 1997);
MERGE INTO YEARS (ID_YEAR, RELEASE_YEAR) KEY(ID_YEAR) VALUES (3, 2009);
MERGE INTO YEARS (ID_YEAR, RELEASE_YEAR) KEY(ID_YEAR) VALUES (4, 2010);
MERGE INTO YEARS (ID_YEAR, RELEASE_YEAR) KEY(ID_YEAR) VALUES (5, 2023);

MERGE INTO GENRES (ID_GENRE, GENRE) KEY(ID_GENRE) VALUES (1, 'Sci-Fi');
MERGE INTO GENRES (ID_GENRE, GENRE) KEY(ID_GENRE) VALUES (2, 'Drama');
MERGE INTO GENRES (ID_GENRE, GENRE) KEY(ID_GENRE) VALUES (3, 'Action');
MERGE INTO GENRES (ID_GENRE, GENRE) KEY(ID_GENRE) VALUES (4, 'Romance');

MERGE INTO ACTORS (ID_ACTOR, ACTOR) KEY(ID_ACTOR) VALUES (1, 'Matthew McConaughey');
MERGE INTO ACTORS (ID_ACTOR, ACTOR) KEY(ID_ACTOR) VALUES (2, 'Anne Hathaway');
MERGE INTO ACTORS (ID_ACTOR, ACTOR) KEY(ID_ACTOR) VALUES (3, 'Leonardo DiCaprio');
MERGE INTO ACTORS (ID_ACTOR, ACTOR) KEY(ID_ACTOR) VALUES (4, 'Kate Winslet');
MERGE INTO ACTORS (ID_ACTOR, ACTOR) KEY(ID_ACTOR) VALUES (5, 'Sam Worthington');
MERGE INTO ACTORS (ID_ACTOR, ACTOR) KEY(ID_ACTOR) VALUES (6, 'Zoe Saldana');